---

services:
  bkway-front:
    image: bkway-front
    pull_policy: never
    build:
      context: ./frontend
      target: development
    ports:
      - 5173:5173
    environment:
      - BACKEND=https://127.0.0.1:3333
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    restart: unless-stopped

  bkway-back:
    image: bkway-back
    pull_policy: never
    build:
      context: ./backend
      target: development
    ports:
      - 3333:3333
    environment:
      - PORT=3333
    volumes:
      - ./data:/usr/data
    restart: unless-stopped
