---

services:
# Just serve dist files instead of doing this `vite preview` mess
  # bkway-front:
  #   image: bkway-front
  #   pull_policy: never
  #   build:
  #     context: ./frontend
  #     target: production
  #   ports:
  #     - 4173:4173
  #   environment:
  #     - BACKEND=http://192.168.0.66:3333
  #   restart: unless-stopped

  bkway-back:
    image: bkway-back
    pull_policy: never
    build:
      context: ./backend
      target: production
    ports:
      - 3333:3333
    environment:
      - PORT=3333
    # Do not mount if database is in memory. Optional otherwise.
    volumes:
      - ./data:/usr/data
    restart: unless-stopped
