---

services:
  bkway-front:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    environment:
      # can be container name
      - BACKEND=https://bkpi.bee-612.space
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    restart: unless-stopped

  bkway-back:
    build:
      context: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./data:/usr/data
      - ./backend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    restart: unless-stopped
