@startuml class_backend

' java -jar C:\ProgramData\chocolatey\lib\plantuml\tools\plantuml.jar -picoweb

' 0 to turn off icons, default 10
' skinparam classAttributeIconSize 0

allowmixing
' left to right direction

artifact "index.ts" as index

index ..> Routes

package Utils {
    class Database {
        + {static} database: Database
        - {static} async ensureDatabase(): Database
    }

    class AdvancedQuery {
        + {static} async searchStops(name: string): Object[]
        + {static} async getNeighbors(stopId: string, time: string): Object[]
        + {static} async function getWalkingNeighbors(stopId: string, distance: number): Object[]

    }

    AdvancedQuery ..> Database
}

Utils.Database ..> Configs

' package Types {
'     class Travel {
'         fromStopId: string
'         fromLat: number
'         fromLon: number
'         toStopId: string
'         toLat: number
'         toLon: number
'         path: [number, number][]
'         minutes: number
'         distance: number
'     }
' }

package Routes {
    class GeojsonRouter {
        + {static} stops()
        + {static} shapes()
    }
    class StopsRouter {
        + {static} search(query: string)
        + {static} neighbors(stopId: string, time: DateTime)
        + {static} nearby(stopId: string, distance: number)
    }
    StopsRouter ..> Utils.AdvancedQuery
}

package Configs {
    artifact "gtfs.config.ts" as gtfsconfig
}

package Models {
    package db {
        package schema {
            artifact "agency"
            artifact "calendar-dates"
            artifact "feed-info"
            artifact "pathways"
            artifact "routes"
            artifact "shapes"
            artifact "stop-times"
            artifact "stops"
            artifact "trips"
        }
    }
}

Configs -[hidden]-> Models

@enduml