@startuml usecase

' java -jar C:\ProgramData\chocolatey\lib\plantuml\tools\plantuml.jar -picoweb

left to right direction
:Felhasználó:

:Felhasználó: ..> (Beállítások módosítása)

(Beállítások módosítása) <.. (Algoritmus választása) : <<include>>
(Algoritmus választása) <.. (Mohó algoritmus) : <<include>>
(Algoritmus választása) <.. (BFS) : <<include>>
(Algoritmus választása) <.. (Dijkstra algoritmus) : <<include>>
(Algoritmus választása) <.. (A* algoritmus) : <<include>>

(Beállítások módosítása) <.. (Algoritmus paramétereinek módosítása) : <<include>>
(Algoritmus paramétereinek módosítása) <.. (Maximális sétatávolság) : <<include>>
(Algoritmus paramétereinek módosítása) <.. (Heurisztika súlya) : <<include>>

:Felhasználó: ..> (Útvonaltervezés)
(Útvonaltervezés) <.. (Indulási idő kiválasztása) : <<extend>>
(Útvonaltervezés) <.. (Induló állomás kiválasztása) : <<extend>>
(Útvonaltervezés) <.. (Érkezési állomás kiválasztása) : <<extend>>

:Felhasználó: ..> (Útvonal megtekintése)
(Útvonal megtekintése) <.. (Tervezés animálása) : <<include>>
(Útvonal megtekintése) <.. (Tervezés lépésenként) : <<include>>

@enduml
